/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class FrmEditorRutas extends javax.swing.JFrame {
    
    private int filaSeleccionada = -1;
    private FrmListaRutas frmPadre;
    
    public FrmEditorRutas() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        txtPrecio.setEditable(false);
        txtPrecio.setFocusable(false); //para que no se seleccione al tabular
        cargarCombos();
        cargarConductores();
        cargarBuses();
    }
    
    private void cargarCombos() {
        // Horarios
        List<String> horarios = MantenimientoRutas.obtenerHorarios();
        for (String h : horarios) {
            cmbHorario.addItem(h);
        }

        // Lugares
        List<String> lugares = MantenimientoRutas.obtenerLugares();
        for (String lugar : lugares) {
            cmbLugarPartida.addItem(lugar);
            cmbLugarLlegada.addItem(lugar);
        }
    }
    
    private void cargarConductores() {
        ArrayList<String> lista = MantenimientoRutas.obtenerConductores();
        for (String cod : lista) {
            cmbConductor.addItem(cod);
        }
    }
    
    private void cargarBuses() {
        ArrayList<String> lista = MantenimientoRutas.obtenerBusesDisponibles();
        for (String bus : lista) {
            cmbBus.addItem(bus);
        }
    }
    
    private void actualizarPrecio() {
        String salida = cmbLugarPartida.getSelectedItem() != null ? cmbLugarPartida.getSelectedItem().toString() : "";
        String llegada = cmbLugarLlegada.getSelectedItem() != null ? cmbLugarLlegada.getSelectedItem().toString() : "";

        String precio = MantenimientoRutas.obtenerPrecioDeRuta(salida, llegada);
        txtPrecio.setText(precio);
    }
    
    public static void abrirConDatos(String[] datos, int filaSeleccionada, FrmListaRutas frmAnterior) {
        FrmEditorRutas editor = new FrmEditorRutas();
        editor.txtFecha.setText(datos[0].trim());
        editor.txtPrecio.setText(datos[1].trim());
        editor.cmbHorario.setSelectedItem(datos[2].trim());
        editor.cmbLugarPartida.setSelectedItem(datos[3].trim());
        editor.cmbLugarLlegada.setSelectedItem(datos[4].trim());
        editor.cmbConductor.setSelectedItem(datos[5].trim());
        editor.cmbBus.setSelectedItem(datos[6].trim());

        editor.filaSeleccionada = filaSeleccionada;
        editor.frmPadre = frmAnterior; // guardamos la instancia anterior
        editor.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cmbHorario = new javax.swing.JComboBox<>();
        cmbLugarPartida = new javax.swing.JComboBox<>();
        cmbLugarLlegada = new javax.swing.JComboBox<>();
        cmbConductor = new javax.swing.JComboBox<>();
        cmbBus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor de la ruta");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Editor de Rutas");

        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha: "));

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio: "));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cmbHorario.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario: "));

        cmbLugarPartida.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar de Partida: "));
        cmbLugarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLugarPartidaActionPerformed(evt);
            }
        });

        cmbLugarLlegada.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar de Llegada: "));
        cmbLugarLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLugarLlegadaActionPerformed(evt);
            }
        });

        cmbConductor.setBorder(javax.swing.BorderFactory.createTitledBorder("Conductor: "));

        cmbBus.setBorder(javax.swing.BorderFactory.createTitledBorder("Bus: "));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbBus, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLugarLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLugarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbLugarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbLugarLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(300, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLugarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLugarPartidaActionPerformed
        actualizarPrecio();
    }//GEN-LAST:event_cmbLugarPartidaActionPerformed

    private void cmbLugarLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLugarLlegadaActionPerformed
        actualizarPrecio();
    }//GEN-LAST:event_cmbLugarLlegadaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String fecha = txtFecha.getText().trim();
        String precio = txtPrecio.getText().trim();
        String horario = cmbHorario.getSelectedItem().toString();
        String salida = cmbLugarPartida.getSelectedItem().toString();
        String llegada = cmbLugarLlegada.getSelectedItem().toString();
        String conductor = cmbConductor.getSelectedItem().toString();
        String bus = cmbBus.getSelectedItem().toString();

        // Validación
        if (fecha.isEmpty() || precio.equalsIgnoreCase("Ruta no permitida")) {
            JOptionPane.showMessageDialog(this, "Por favor completa los campos correctamente.");
            return;
        }

        String[] nuevaRuta = {fecha, precio, horario, salida, llegada, conductor, bus};

        MantenimientoRutas.actualizarRutaEnArchivo(filaSeleccionada, nuevaRuta);

        JOptionPane.showMessageDialog(this, "Ruta actualizada correctamente.");

        this.dispose(); // Cierra este formulario (FrmEditorRutas)

        if (frmPadre != null) {
            frmPadre.dispose(); // Cierra el formulario anterior (FrmListaRutas)
        }

        new FrmListaRutas().setVisible(true); // Abre uno nuevo con datos actualizados
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditorRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditorRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditorRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditorRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditorRutas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbBus;
    private javax.swing.JComboBox<String> cmbConductor;
    private javax.swing.JComboBox<String> cmbHorario;
    private javax.swing.JComboBox<String> cmbLugarLlegada;
    private javax.swing.JComboBox<String> cmbLugarPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
