/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class FrmEditorEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form FrmEditorEmpleados
     */
    public FrmEditorEmpleados() {
        initComponents();
        cargarCodigos();
    }
    
    private void cargarCodigos() {
        ArchivoEmpleado archivo = new ArchivoEmpleado();
        ArrayList<RegistroEmpleados> empleados = archivo.obtenerEmpleados();

        cmbCodigo.removeAllItems();
        cmbCodigo.addItem("-------SELECCIONE-------");
        for (RegistroEmpleados emp : empleados) {
            cmbCodigo.addItem(emp.getCodigo());
        }
    }
    
    private void limpiarCampos() {
    txtNombres.setText("");
    txtApellidos.setText("");
    txtDNI.setText("");
    txtCorreo.setText("");
    txtTelefono.setText("");
    txtEdad.setText("");

    cmbOficina.setSelectedIndex(0);
    cmbCargo.setSelectedIndex(0);
    cmbSexo.setSelectedIndex(0);
    cmbCodigo.setSelectedIndex(0); // Volver a "-------SELECCIONE-------"
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDNI = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        lblTituloActualizarEmpleado = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        lblOficina = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        cmbOficina = new javax.swing.JComboBox<>();
        lblDNI = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnRetroceder = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        cmbCodigo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblSexo.setText("Sexo:");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------SELECCIONE-------", "Masculino", "Femenino" }));

        lblTituloActualizarEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTituloActualizarEmpleado.setText("Actualiza datos del empleado:");

        lblEdad.setText("Edad:");

        lblOficina.setText("Oficina:");

        lblCodigo.setText("Codigo:");

        lblCargo.setText("Cargo:");

        lblNombres.setText("Nombres:");

        cmbOficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------SELECCIONE-------", "Lima", "Cañete", "Cerro Azul", "Ica", "Atíco", "Camana", "Alto Siguas", "Arequipa" }));

        lblDNI.setText("DNI:");

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------SELECCIONE-------", "Operario de Rutas", "Conductor", "Counter", "Gerente de Finanzas", "Analista de Viajes", "Director de Logística", "Responsable de Recursos Humanos" }));

        lblCorreo.setText("Correo:");

        lblTelefono.setText("Telefono:");

        lblApellidos.setText("Apellidos:");

        btnRetroceder.setText("Retroceder");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        cmbCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------SELECCIONE-------" }));
        cmbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addComponent(cmbCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEdad)
                                        .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEdad)
                                        .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTelefono)
                                        .addComponent(lblCorreo)
                                        .addComponent(lblOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbOficina, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbCargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(txtDNI))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblTituloActualizarEmpleado)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblTituloActualizarEmpleado)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(cmbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOficina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        setSize(new java.awt.Dimension(620, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
            FrmRegistroEmpleados formadim = new FrmRegistroEmpleados();
            formadim.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        String codigo = (String) cmbCodigo.getSelectedItem();

        if (codigo == null || codigo.equals("-------SELECCIONE-------")) {
                JOptionPane.showMessageDialog(this, "Seleccione un código válido.");
                return;
        }

        ArchivoEmpleado archivo = new ArchivoEmpleado();
        ArrayList<RegistroEmpleados> empleados = archivo.obtenerEmpleados();
        RegistroEmpleados original = null;

        for (RegistroEmpleados emp : empleados) {
                if (emp.getCodigo().equals(codigo)) {
                        original = emp;
                        break;
                }
        }

        if (original == null) {
                JOptionPane.showMessageDialog(this, "Empleado no encontrado.");
                return;
        }

        try {
                // Mantener original si el campo está vacío
                String nombres = txtNombres.getText().isEmpty() ? original.getNombres() : txtNombres.getText();
                String apellidos = txtApellidos.getText().isEmpty() ? original.getApellidos() : txtApellidos.getText();
                String dni = txtDNI.getText().isEmpty() ? original.getDni() : txtDNI.getText();
                String correo = txtCorreo.getText().isEmpty() ? original.getCorreo() : txtCorreo.getText().toLowerCase();
                String telefono = txtTelefono.getText().isEmpty() ? original.getTelefono() : txtTelefono.getText();
                String oficina = cmbOficina.getSelectedIndex() <= 0 ? original.getOficina() : cmbOficina.getSelectedItem().toString();
                String cargo = cmbCargo.getSelectedIndex() <= 0 ? original.getCargo() : cmbCargo.getSelectedItem().toString();
                String sexo = cmbSexo.getSelectedIndex() <= 0 ? original.getSexo() : cmbSexo.getSelectedItem().toString();
                int edad = txtEdad.getText().isEmpty() ? original.getEdad() : Integer.parseInt(txtEdad.getText());

                // Validaciones de formato
                if (!dni.matches("\\d{8}")) {
                        JOptionPane.showMessageDialog(this, "El DNI debe tener 8 dígitos numéricos.");
                        return;
                }

                if (!correo.endsWith("@gmail.com") && !correo.endsWith("@outlook.com")) {
                        JOptionPane.showMessageDialog(this, "El correo debe terminar en @gmail.com o @outlook.com.");
                        return;
                }

                if (!telefono.matches("9\\d{8}")) {
                        JOptionPane.showMessageDialog(this, "El teléfono debe comenzar con 9 y tener 9 dígitos.");
                        return;
                }

                if (edad < 18 || edad > 65) {
                        JOptionPane.showMessageDialog(this, "La edad debe estar entre 18 y 65 años.");
                        return;
                }

                // Verificación de datos repetidos en otros empleados (solo DNI, Teléfono, Correo)
                ArrayList<String> conflictos = new ArrayList<>();
                String nombreConflicto = "";

                for (RegistroEmpleados emp : empleados) {
                        if (emp.getCodigo().equals(codigo)) continue; // Ignorar al propio empleado

                        boolean coincide = false;

                        if (emp.getDni().equals(dni)) {
                                conflictos.add("DNI");
                                coincide = true;
                        }
                        if (emp.getTelefono().equals(telefono)) {
                                conflictos.add("Teléfono");
                                coincide = true;
                        }
                        if (emp.getCorreo().equalsIgnoreCase(correo)) {
                                conflictos.add("Correo electrónico");
                                coincide = true;
                        }

                        if (coincide && nombreConflicto.isEmpty()) {
                                nombreConflicto = emp.getNombres() + " " + emp.getApellidos();
                        }
                }

                if (!conflictos.isEmpty()) {
                        String mensaje = "No se puede actualizar al empleado \"" + nombres + " " + apellidos + "\" porque los siguientes datos ya están registrados por otro empleado"
                                        + (nombreConflicto.isEmpty() ? "" : " llamado \"" + nombreConflicto + "\"") + ":\n- "
                                        + String.join("\n- ", conflictos);
                        JOptionPane.showMessageDialog(this, mensaje);
                        return;
                }

                // Crear objeto actualizado
                RegistroEmpleados actualizado = new RegistroEmpleados(
                        codigo, nombres, apellidos, dni, correo,
                        telefono, oficina, cargo, sexo, edad
                );

                boolean exito = archivo.actualizarEmpleado(actualizado);

                if (exito) {
                        JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");
                        limpiarCampos(); // ← Limpia campos y restablece combo
                } else {
                        JOptionPane.showMessageDialog(this, "No se pudo actualizar el empleado.");
                }
        } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Edad inválida. Ingrese un número.");
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void cmbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodigoActionPerformed
        String codigoSeleccionado = (String) cmbCodigo.getSelectedItem();
        if (codigoSeleccionado == null || codigoSeleccionado.equals("-------SELECCIONE-------")) return;

        ArchivoEmpleado archivo = new ArchivoEmpleado();
        ArrayList<RegistroEmpleados> empleados = archivo.obtenerEmpleados();

        for (RegistroEmpleados emp : empleados) {
            if (emp.getCodigo().equals(codigoSeleccionado)) {
                txtNombres.setText(emp.getNombres());
                txtApellidos.setText(emp.getApellidos());
                txtDNI.setText(emp.getDni());
                txtCorreo.setText(emp.getCorreo());
                txtTelefono.setText(emp.getTelefono());
                cmbOficina.setSelectedItem(emp.getOficina());
                cmbCargo.setSelectedItem(emp.getCargo());
                txtEdad.setText(String.valueOf(emp.getEdad()));
                cmbSexo.setSelectedItem(emp.getSexo());
                break;
            }
        }

    }//GEN-LAST:event_cmbCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditorEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditorEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditorEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditorEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditorEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbCodigo;
    private javax.swing.JComboBox<String> cmbOficina;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblOficina;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloActualizarEmpleado;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
