package Proyecto;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class FrmEnvioObjetos extends javax.swing.JFrame {

    private void iniciarRelojEnFecha() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LocalDateTime ahora = LocalDateTime.now();
                txtFecha.setText(ahora.format(formatter));
            }
        });

        timer.start();
    }
    
    
    private void mostrarDatosObjetoSeleccionado() {
        String codigoSeleccionado = (String) cbmCodigo.getSelectedItem();
        if (codigoSeleccionado == null || codigoSeleccionado.equals("Selecciona un código")) return;

        Logistica obj = MantenimientoLogistica.buscarObjetoPorCodigo(codigoSeleccionado);
        if (obj != null) {
            txtFecha.setText(obj.getFecha());
            txtObjeto.setText(obj.getObjeto());
            txtCantidad.setText(String.valueOf(obj.getCantidad()));
            txtOficina.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el objeto para el código seleccionado.");
        }
    }
    
    public FrmEnvioObjetos() {
        initComponents();
        MantenimientoLogistica.cargarCodigosEdicion(cbmCodigo); // Método que llena el combo
        iniciarRelojEnFecha(); //Este método actualiza txtFecha cada segundo
        
        // Desactivar edición y tabulación de los campos que no deben modificarse
        txtFecha.setEditable(false);
        txtFecha.setFocusable(false);

        txtObjeto.setEditable(false);
        txtObjeto.setFocusable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtObjeto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        cbmCodigo = new javax.swing.JComboBox<>();
        txtOficina = new javax.swing.JTextField();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuRegistroObjetos = new javax.swing.JMenu();
        menuItemRetroceder = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtObjeto.setBorder(javax.swing.BorderFactory.createTitledBorder("Objeto: "));

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad: "));

        btnEditar.setText("Enviar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel1.setText("Distribución de Objetos Logísticos a Áreas Requeridas");

        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha: "));

        cbmCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo: "));
        cbmCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmCodigoActionPerformed(evt);
            }
        });

        txtOficina.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina: "));

        menuRegistroObjetos.setText("Opciones");

        menuItemRetroceder.setText("Regresar al Menú");
        menuItemRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRetrocederActionPerformed(evt);
            }
        });
        menuRegistroObjetos.add(menuItemRetroceder);

        menuBarPrincipal.add(menuRegistroObjetos);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbmCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtOficina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(txtObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(709, 362));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbmCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmCodigoActionPerformed
         mostrarDatosObjetoSeleccionado();
    }//GEN-LAST:event_cbmCodigoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String codigo = (String) cbmCodigo.getSelectedItem();
        String fecha = txtFecha.getText().trim();
        String objeto = txtObjeto.getText().trim();
        String cantidadStr = txtCantidad.getText().trim();
        String area = txtOficina.getText().trim();

        if (codigo == null || codigo.equals("Selecciona un código") ||
            fecha.isEmpty() || objeto.isEmpty() || cantidadStr.isEmpty() || area.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }

        int cantidad;
        try {
            cantidad = Integer.parseInt(cantidadStr);
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.");
            return;
        }

        // Restar cantidad en objetos.txt
        boolean operacionExitosa = MantenimientoLogistica.descontarCantidadObjeto(codigo, cantidad);
        if (!operacionExitosa) {
            JOptionPane.showMessageDialog(this, "No hay suficiente stock para enviar esa cantidad.");
            return;
        }

        // Registrar el envío en envios.txt
        Logistica envio = new Logistica(codigo, fecha, objeto, cantidad, area);
        MantenimientoLogistica.registrarEnvio(envio);

        JOptionPane.showMessageDialog(this, "Envío registrado y stock actualizado correctamente.");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void menuItemRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRetrocederActionPerformed
        FrmDirectorLogistica formdirectorlogistica = new FrmDirectorLogistica();
        formdirectorlogistica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemRetrocederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEnvioObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEnvioObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEnvioObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEnvioObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEnvioObjetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> cbmCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenuItem menuItemRetroceder;
    private javax.swing.JMenu menuRegistroObjetos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtObjeto;
    private javax.swing.JTextField txtOficina;
    // End of variables declaration//GEN-END:variables
}
