/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class FrmInventarioObjetos extends javax.swing.JFrame {

    /**
     * Creates new form FrmInventarioObjetos
     */
    public FrmInventarioObjetos() {
        initComponents();

        // Configurar el modelo de la tabla con las columnas necesarias
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Fecha");
        modelo.addColumn("Objeto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Área"); // Asegúrate de agregar la columna "Área"

        // Establecer el modelo en el JTable
        TableObjetosInfo.setModel(modelo);

        // Llamar a cargarDatos() para cargar los datos del archivo en el JTable
        MantenimientoLogistica.cargarDatos(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableObjetosInfo = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txtBusquedaCodigo = new javax.swing.JTextField();
        btnIniciarCodigo = new javax.swing.JButton();
        btnReiniciar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtBusquedaFecha = new javax.swing.JTextField();
        btnIniciarFecha = new javax.swing.JButton();
        btnReiniciar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBusquedaObjeto = new javax.swing.JTextField();
        btnIniciarObjeto = new javax.swing.JButton();
        btnReiniciar3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnIniciarArea = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        txtBusquedaArea = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuListaClientes = new javax.swing.JMenu();
        menuItemRegresarMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Objetos Logísticos");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblTitulo.setText("Registro de Objetos Logísticos - Vista de Datos");

        TableObjetosInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableObjetosInfo);

        txtBusquedaCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda: "));

        btnIniciarCodigo.setText("Iniciar");
        btnIniciarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarCodigoActionPerformed(evt);
            }
        });

        btnReiniciar1.setText("Reiniciar");
        btnReiniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(txtBusquedaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnIniciarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReiniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBusquedaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Codigo", jPanel4);

        txtBusquedaFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda: "));

        btnIniciarFecha.setText("Iniciar");
        btnIniciarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarFechaActionPerformed(evt);
            }
        });

        btnReiniciar2.setText("Reiniciar");
        btnReiniciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(txtBusquedaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnIniciarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReiniciar2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBusquedaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fecha", jPanel1);

        txtBusquedaObjeto.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda: "));

        btnIniciarObjeto.setText("Iniciar");
        btnIniciarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarObjetoActionPerformed(evt);
            }
        });

        btnReiniciar3.setText("Reiniciar");
        btnReiniciar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(txtBusquedaObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnIniciarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReiniciar3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBusquedaObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Objeto", jPanel2);

        btnIniciarArea.setText("Iniciar");
        btnIniciarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarAreaActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        txtBusquedaArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda: "));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(txtBusquedaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIniciarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtBusquedaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Area", jPanel3);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        menuListaClientes.setText("Opciones");

        menuItemRegresarMenu.setText("Regresar al Menú");
        menuItemRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegresarMenuActionPerformed(evt);
            }
        });
        menuListaClientes.add(menuItemRegresarMenu);

        menuBarPrincipal.add(menuListaClientes);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addComponent(lblTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitulo)
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(775, 735));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarCodigoActionPerformed
        // Obtener el valor de búsqueda de Código
        String codigo = txtBusquedaCodigo.getText().toLowerCase();

        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TableObjetosInfo.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de agregar los resultados filtrados

        try (BufferedReader br = new BufferedReader(new FileReader("objetos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                // Filtrar según el código
                if (codigo.isEmpty() || datos[0].toLowerCase().contains(codigo)) {
                    modelo.addRow(datos); // Agregar la fila filtrada a la tabla
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIniciarCodigoActionPerformed

    private void btnIniciarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarFechaActionPerformed
        // Obtener el valor de búsqueda de Fecha
        String fecha = txtBusquedaFecha.getText().toLowerCase();

        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TableObjetosInfo.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de agregar los resultados filtrados

        try (BufferedReader br = new BufferedReader(new FileReader("objetos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                // Filtrar según la fecha
                if (fecha.isEmpty() || datos[1].toLowerCase().contains(fecha)) {
                    modelo.addRow(datos); // Agregar la fila filtrada a la tabla
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIniciarFechaActionPerformed

    private void btnIniciarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarObjetoActionPerformed
        // Obtener el valor de búsqueda de Objeto
        String objeto = txtBusquedaObjeto.getText().toLowerCase();

        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TableObjetosInfo.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de agregar los resultados filtrados

        try (BufferedReader br = new BufferedReader(new FileReader("objetos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                // Filtrar según el objeto
                if (objeto.isEmpty() || datos[2].toLowerCase().contains(objeto)) {
                    modelo.addRow(datos); // Agregar la fila filtrada a la tabla
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIniciarObjetoActionPerformed

    private void btnIniciarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarAreaActionPerformed
        // Obtener el valor ingresado en el TextField para el área
        String area = txtBusquedaArea.getText().toLowerCase(); // Obtener el texto del TextField

        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TableObjetosInfo.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de agregar los resultados filtrados

        try (BufferedReader br = new BufferedReader(new FileReader("objetos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                // Filtrar según el área ingresada en el TextField
                if (area.isEmpty() || datos[4].toLowerCase().contains(area)) {
                    modelo.addRow(datos); // Agregar la fila filtrada a la tabla
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIniciarAreaActionPerformed

    private void btnReiniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciar1ActionPerformed
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TableObjetosInfo.getModel();

        // Limpiar la tabla antes de recargar los datos
        modelo.setRowCount(0);

        // Llamar al método para cargar todos los datos del archivo en la tabla
        MantenimientoLogistica.cargarDatos(modelo);
    }//GEN-LAST:event_btnReiniciar1ActionPerformed

    private void btnReiniciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciar2ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TableObjetosInfo.getModel();

        // Limpiar la tabla antes de recargar los datos
        modelo.setRowCount(0);

        // Llamar al método para cargar todos los datos del archivo en la tabla
        MantenimientoLogistica.cargarDatos(modelo);
    }//GEN-LAST:event_btnReiniciar2ActionPerformed

    private void btnReiniciar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciar3ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TableObjetosInfo.getModel();

        // Limpiar la tabla antes de recargar los datos
        modelo.setRowCount(0);

        // Llamar al método para cargar todos los datos del archivo en la tabla
        MantenimientoLogistica.cargarDatos(modelo);
    }//GEN-LAST:event_btnReiniciar3ActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TableObjetosInfo.getModel();

        // Limpiar la tabla antes de recargar los datos
        modelo.setRowCount(0);

        // Llamar al método para cargar todos los datos del archivo en la tabla
        MantenimientoLogistica.cargarDatos(modelo);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = TableObjetosInfo.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
            return;
        }

        String codigo = TableObjetosInfo.getValueAt(filaSeleccionada, 0).toString(); // Columna 0 = Código

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar el objeto con código " + codigo + "?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            MantenimientoLogistica.eliminarObjetoPorCodigo(codigo);
            ((DefaultTableModel) TableObjetosInfo.getModel()).removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "Objeto eliminado correctamente.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void menuItemRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegresarMenuActionPerformed
        FrmDirectorLogistica formdirectorlogistica = new FrmDirectorLogistica();
        formdirectorlogistica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemRegresarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventarioObjetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableObjetosInfo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIniciarArea;
    private javax.swing.JButton btnIniciarCodigo;
    private javax.swing.JButton btnIniciarFecha;
    private javax.swing.JButton btnIniciarObjeto;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnReiniciar1;
    private javax.swing.JButton btnReiniciar2;
    private javax.swing.JButton btnReiniciar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenuItem menuItemRegresarMenu;
    private javax.swing.JMenu menuListaClientes;
    private javax.swing.JTextField txtBusquedaArea;
    private javax.swing.JTextField txtBusquedaCodigo;
    private javax.swing.JTextField txtBusquedaFecha;
    private javax.swing.JTextField txtBusquedaObjeto;
    // End of variables declaration//GEN-END:variables
}
