/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author sergi
 */
public class FrmListaBuses extends javax.swing.JFrame {

    DefaultTableModel modelo;
    MantenimientoBuses mantenimiento;
    
    private void personalizarBoton(JButton boton) {
        Color fondo = new Color(0, 120, 215); // Azul moderno
        Color fondoHover = new Color(0, 150, 255);
        Color texto = Color.WHITE;

        boton.setBackground(fondo);
        boton.setForeground(texto);
        boton.setFocusPainted(false);
        boton.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20)); // Padding
        boton.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        boton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Quitar efectos de Look&Feel predeterminados
        boton.setContentAreaFilled(true);
        boton.setOpaque(true);

        // Efecto hover
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton.setBackground(fondoHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton.setBackground(fondo);
            }
        });
    }
    
    public FrmListaBuses() {
        initComponents();
        String[] nombreColumna = {"Placa","Model","Marca","Estado","Usos"};
        modelo= new DefaultTableModel(nombreColumna,0);
        tblListaBuses.setModel(modelo);
        tblListaBuses.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblListaBuses.setShowGrid(false);
        tblListaBuses.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        mantenimiento = new MantenimientoBuses();
        
        cargarBusesDesdeArchivo();
        
        personalizarBoton(btnEliminarBus);
        personalizarBoton(btnFiltrarPorEstado);
        personalizarBoton(btnMostrarLista);
        personalizarBoton(btnfiltarPorPlaca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpFiltros = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txtIngresePlaca = new javax.swing.JTextField();
        btnfiltarPorPlaca = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnFiltrarPorEstado = new javax.swing.JButton();
        cbFiltroPorEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaBuses = new javax.swing.JTable();
        lblListadoRutasRegistradas = new javax.swing.JLabel();
        btnMostrarLista = new javax.swing.JButton();
        btnEliminarBus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Buses");
        setResizable(false);

        txtIngresePlaca.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la Placa:"));

        btnfiltarPorPlaca.setText("Filtrar");
        btnfiltarPorPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltarPorPlacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(txtIngresePlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btnfiltarPorPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngresePlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfiltarPorPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tpFiltros.addTab("Filtro por Placa", jPanel4);

        btnFiltrarPorEstado.setText("Filtrar");
        btnFiltrarPorEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarPorEstadoActionPerformed(evt);
            }
        });

        cbFiltroPorEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------Seleccione-----------", "Listo", "En mantenimiento", "Malogrado" }));
        cbFiltroPorEstado.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(cbFiltroPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(btnFiltrarPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnFiltrarPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbFiltroPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tpFiltros.addTab("Filtro por Estado", jPanel3);

        tblListaBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaBuses);

        lblListadoRutasRegistradas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblListadoRutasRegistradas.setText("Listado de todos los buses registrados");

        btnMostrarLista.setText("Mostrar toda la lista");
        btnMostrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarListaActionPerformed(evt);
            }
        });

        btnEliminarBus.setText("Eliminar Bus");
        btnEliminarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tpFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblListadoRutasRegistradas)
                        .addGap(180, 180, 180))))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarBus, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblListadoRutasRegistradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(tpFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnMostrarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnEliminarBus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        setSize(new java.awt.Dimension(810, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnfiltarPorPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltarPorPlacaActionPerformed
        filtrarPorTexto(0, txtIngresePlaca.getText());
    }//GEN-LAST:event_btnfiltarPorPlacaActionPerformed

    private void btnFiltrarPorEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarPorEstadoActionPerformed
        String estadoSeleccionado = cbFiltroPorEstado.getSelectedItem().toString().trim();
        if (estadoSeleccionado.equals("------------Seleccione-----------")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un estado.");
            return;
        }

        filtrarPorTexto(3, estadoSeleccionado); // 3 es el índice de la columna de "Estado"
    }//GEN-LAST:event_btnFiltrarPorEstadoActionPerformed

    private void btnMostrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarListaActionPerformed
        cargarBusesDesdeArchivo();
    }//GEN-LAST:event_btnMostrarListaActionPerformed

    private void btnEliminarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBusActionPerformed
        eliminarBusSeleccionado();
        cargarBusesDesdeArchivo();
    }//GEN-LAST:event_btnEliminarBusActionPerformed

    private void cargarBusesDesdeArchivo() {
        //Asegurar que la tabla vuelva a usar el modelo original
        tblListaBuses.setModel(modelo);
        modelo.setRowCount(0); 

        try (java.util.Scanner scanner = new java.util.Scanner(new java.io.File("buses.txt"))) {
            while (scanner.hasNextLine()) {
                String linea = scanner.nextLine();
                String[] datos = linea.split(";");
                if (datos.length == 5) {
                    modelo.addRow(datos);
                }
            }
        } catch (java.io.FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "No se encontró el archivo de buses.");
        }
    }
    
    private void filtrarPorTexto(int columna, String texto) {
        DefaultTableModel modeloFiltrado = new DefaultTableModel();
        // Copiar estructura por columna
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            modeloFiltrado.addColumn(modelo.getColumnName(i));
        }
        boolean encontrado = false;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String celda = modelo.getValueAt(i, columna).toString().trim().toLowerCase();
            System.out.println("Comparando: " + celda + " con " + texto.toLowerCase());  // Para depuración
            if (celda.contains(texto.toLowerCase())) {
                Object[] fila = new Object[modelo.getColumnCount()];
                for (int j = 0; j < modelo.getColumnCount(); j++) {
                    fila[j] = modelo.getValueAt(i, j);
                }
                modeloFiltrado.addRow(fila);
                encontrado = true;
            }
        }
        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados válidos en esta categoría.", "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        }
        tblListaBuses.setModel(modeloFiltrado);
    }
    
    private void eliminarBusSeleccionado() {
        int fila = tblListaBuses.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
            return;
        }
        String codigoAEliminar = tblListaBuses.getValueAt(fila, 0).toString(); //Código del empleado
        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar al bus con codigo " + codigoAEliminar + "?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        java.io.File archivoOriginal = new java.io.File("buses.txt");
        java.io.File archivoTemporal = new java.io.File("buses_temp.txt");
        try (
            java.util.Scanner lector = new java.util.Scanner(archivoOriginal);
            java.io.PrintWriter escritor = new java.io.PrintWriter(archivoTemporal)
        ) {
            while (lector.hasNextLine()) {
                String linea = lector.nextLine();
                if (!linea.startsWith(codigoAEliminar + ";")) {
                    escritor.println(linea);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar del archivo: " + e.getMessage());
            return;
        }
        archivoOriginal.delete();
        archivoTemporal.renameTo(archivoOriginal);
        JOptionPane.showMessageDialog(this, "Bus eliminado correctamente.");
        cargarBusesDesdeArchivo(); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListaBuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarBus;
    private javax.swing.JButton btnFiltrarPorEstado;
    private javax.swing.JButton btnMostrarLista;
    private javax.swing.JButton btnfiltarPorPlaca;
    private javax.swing.JComboBox<String> cbFiltroPorEstado;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListadoRutasRegistradas;
    private javax.swing.JTable tblListaBuses;
    private javax.swing.JTabbedPane tpFiltros;
    private javax.swing.JTextField txtIngresePlaca;
    // End of variables declaration//GEN-END:variables
}
