/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

public class FrmRegistroObjetos extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistroObjetos
     */
    public FrmRegistroObjetos() {
        initComponents();
    
    // Hacer que el campo de fecha no sea editable
    txtFecha.setEditable(false);
    // Evitar que el campo sea enfocado (y por lo tanto no se puede tabular)
    txtFecha.setFocusable(false);
    
    // Crear el temporizador que actualiza la fecha en el textfield cada segundo
    Timer timer = new Timer(1000, e -> {
        // Llamar al método de MantenimientoLogistica para obtener la fecha y hora actuales
        String fecha = MantenimientoLogistica.obtenerFechaYHora();
        
        // Setear la fecha en el campo txtFecha
        txtFecha.setText(fecha);
    });
    timer.start(); // Inicia el temporizador
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtObjeto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuRegistroObjetos = new javax.swing.JMenu();
        menuItemInventarioObjetos = new javax.swing.JMenuItem();
        menuItemRetroceder = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Registro de Objetos Logísticos");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblTitulo.setText("Registro de Equipos y Suministros de Logística");

        txtArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Area: "));

        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha: "));

        txtObjeto.setBorder(javax.swing.BorderFactory.createTitledBorder("Objeto: "));

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad: "));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo: "));

        menuRegistroObjetos.setText("Opciones");

        menuItemInventarioObjetos.setText("Inventario de objetos");
        menuItemInventarioObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInventarioObjetosActionPerformed(evt);
            }
        });
        menuRegistroObjetos.add(menuItemInventarioObjetos);

        menuItemRetroceder.setText("Regresar al Menú");
        menuItemRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRetrocederActionPerformed(evt);
            }
        });
        menuRegistroObjetos.add(menuItemRetroceder);

        menuBarPrincipal.add(menuRegistroObjetos);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(txtObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(703, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String codigo = txtCodigo.getText().trim();

        LocalDateTime ahora = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String fecha = ahora.format(formatter);

        String objeto = txtObjeto.getText().trim();
        String cantidadStr = txtCantidad.getText().trim();
        String area = txtArea.getText().trim();

        if (codigo.isEmpty() || objeto.isEmpty() || cantidadStr.isEmpty() || area.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos.");
            return;
        }

        int cantidad;
        try {
            cantidad = Integer.parseInt(cantidadStr);
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad ingresada es incorrecta.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.");
            return;
        }
        if (MantenimientoLogistica.objetoExisteConOtroCodigo(codigo, objeto)) {
            JOptionPane.showMessageDialog(this, "El objeto \"" + objeto + "\" ya está registrado con otro código. Usa el mismo código para actualizarlo.");
            return;
        }

        Logistica nuevoObjeto = new Logistica(codigo, fecha, objeto, cantidad, area);
        MantenimientoLogistica.guardarOActualizarObjeto(nuevoObjeto);

        JOptionPane.showMessageDialog(this, "Objeto registrado o actualizado correctamente.");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void menuItemRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRetrocederActionPerformed
        FrmDirectorLogistica formdirectorlogistica = new FrmDirectorLogistica();
        formdirectorlogistica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemRetrocederActionPerformed

    private void menuItemInventarioObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInventarioObjetosActionPerformed
        FrmInventarioObjetos forminveobje = new FrmInventarioObjetos();
        forminveobje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemInventarioObjetosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistroObjetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenuItem menuItemInventarioObjetos;
    private javax.swing.JMenuItem menuItemRetroceder;
    private javax.swing.JMenu menuRegistroObjetos;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtObjeto;
    // End of variables declaration//GEN-END:variables
}
